import { mkdir, writeFile } from "node:fs/promises";
import { dirname, relative } from "node:path";
import type { Table } from "drizzle-orm";
import { createLoader } from "../config/load.js";
import type { ResolvedConfig } from "../config/types.js";
import { loadFixtures } from "../fixtures/load.js";
import { loadSchema } from "../schema/introspect.js";
import type { SchemaEntry } from "../types.js";
import { SaatError } from "../util/errors.js";

export interface GenerateResult {
  path: string;
  namespaces: string[];
}

/** Turn an absolute module path into a relative, extensionless import specifier. */
function importSpecifier(fromDir: string, toFile: string): string {
  let rel = relative(fromDir, toFile).replace(/\\/g, "/");
  rel = rel.replace(/\.[cm]?[jt]s$/, "");
  if (!rel.startsWith(".")) rel = `./${rel}`;
  return rel;
}

const VALID_IDENT = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

/**
 * Generate `.drizzle-saat/types.d.ts`: a module augmentation mapping each fixture
 * namespace to its table's `InferSelectModel`, so `ref()` and `.where()` are
 * type-checked and autocompleted across files. Regenerated before every run.
 */
export async function generateTypes(
  config: ResolvedConfig,
  deps: { jiti?: ReturnType<typeof createLoader> } = {},
): Promise<GenerateResult> {
  const jiti = deps.jiti ?? createLoader();
  const schema = await loadSchema(config.schemaPaths, config.dialect, jiti);
  const fixtures = await loadFixtures(config.fixturesDir, jiti);

  // namespace -> schema entry (first definition wins; run-time enforces uniqueness).
  const namespaceEntry = new Map<string, SchemaEntry>();
  // namespace -> keyed-row keys, so `ref(ns, key)` validates the key.
  const namespaceKeys = new Map<string, string[]>();
  for (const { fixture } of fixtures) {
    for (const seed of fixture.seeds) {
      if (namespaceEntry.has(seed.namespace)) continue;
      const entry = schema.get(seed.table as Table);
      if (entry) {
        namespaceEntry.set(seed.namespace, entry);
        const keys = seed.rows ? Object.keys(seed.rows) : [];
        if (keys.length > 0) namespaceKeys.set(seed.namespace, keys);
      }
    }
  }

  const outDir = dirname(config.typesOut);
  await mkdir(outDir, { recursive: true });

  // One import alias per distinct source file.
  const aliasByFile = new Map<string, string>();
  const importLines: string[] = [];
  const namespaceLines: string[] = [];
  const refValueLines: string[] = [];
  const keyLines: string[] = [];

  // Plain codepoint sort (not localeCompare) so generated output is identical
  // across machines and locales — the .d.ts must be reproducible.
  for (const [namespace, entry] of [...namespaceEntry].sort(([a], [b]) =>
    a < b ? -1 : a > b ? 1 : 0,
  )) {
    let alias = aliasByFile.get(entry.sourceFile);
    if (!alias) {
      alias = `__schema_${aliasByFile.size}`;
      aliasByFile.set(entry.sourceFile, alias);
      importLines.push(
        `import type * as ${alias} from "${importSpecifier(outDir, entry.sourceFile)}";`,
      );
    }
    const access = VALID_IDENT.test(entry.exportName)
      ? `${alias}.${entry.exportName}`
      : `${alias}[${JSON.stringify(entry.exportName)}]`;
    namespaceLines.push(`    "${namespace}": InferSelectModel<typeof ${access}>;`);
    // Single-PK namespaces can be ref targets; expose the PK's value type so
    // `ref("ns")` is typed as the id it resolves to.
    if (entry.primaryKeys.length === 1) {
      const pk = entry.primaryKeys[0]!;
      refValueLines.push(
        `    "${namespace}": InferSelectModel<typeof ${access}>[${JSON.stringify(pk)}];`,
      );
    }
    // Keyed-row keys for this namespace, so `ref(ns, key)` validates the key.
    const keys = namespaceKeys.get(namespace);
    if (keys) {
      const union = keys.map((k) => JSON.stringify(k)).join(" | ");
      keyLines.push(`    "${namespace}": ${union};`);
    }
  }

  if (namespaceLines.length === 0) {
    throw new SaatError(
      "no fixtures found to generate types for. Add fixtures under your drizzle-saat directory.",
    );
  }

  const content = `// AUTO-GENERATED by drizzle-saat. Do not edit.
/* eslint-disable */
import type { InferSelectModel } from "drizzle-orm";
${importLines.join("\n")}

declare module "drizzle-saat" {
  interface SaatNamespaces {
${namespaceLines.join("\n")}
  }
  interface SaatRefValues {
${refValueLines.join("\n")}
  }
  interface SaatNamespaceKeys {
${keyLines.join("\n")}
  }
}
`;

  await writeFile(config.typesOut, content, "utf8");
  return { path: config.typesOut, namespaces: [...namespaceEntry.keys()] };
}
